Repository sourcegit-scm/sourcegit, pull requests merged in 2024-08, with the labels that each got.

#323 Enhance German translation
  src/Resources/Locales/de_DE.axaml
Labels: enhancement

#349 Enhance German translation (2)
  src/Resources/Locales/de_DE.axaml
Labels: enhancement

#353 Code review suggestions for German translation
  src/Resources/Locales/de_DE.axaml
Labels: enhancement

#356 Automatic CI releases
  .github/workflows/ci.yml
  .github/workflows/package.yml
  .github/workflows/release.yml
  build/build.linux.sh
  build/ci/package.linux.sh
  build/ci/package.osx-app.sh
  build/ci/package.windows-portable.sh
  build/resources/appimage/sourcegit.appdata.xml
  build/resources/deb/DEBIAN/control
  build/resources/deb/DEBIAN/postinst
  build/resources/deb/DEBIAN/postrm
  build/resources/rpm/SPECS/build.spec
Labels: enhancement

#358 Add German translation 'open app data dir'
  src/Resources/Locales/de_DE.axaml
Labels: localization

#371 New keys for german translation
  src/Resources/Locales/de_DE.axaml
Labels: localization

#377 Support iTerm2 in MacOS
  src/Native/MacOS.cs
Labels: enhancement, os-macos

#381 Fix foreground color in tooltip on primary button
  src/Resources/Styles.axaml
Labels: bug

#383 fix: invalidate counter visual (#338)
  src/Views/Repository.axaml.cs
Labels: bug

#387 ux: Preference fit to content width
  src/Views/Preference.axaml
Labels: enhancement

#392 Prevent executing an executable file with the same name as the directory
  src/Native/Windows.cs
Labels: bug

#399 Add German NativeWindowFrame + FirstParentOption key
  src/Resources/Locales/de_DE.axaml
Labels: localization

#415 enhancement: Some file operation optimizations
  src/ViewModels/CommitDetail.cs
  src/ViewModels/Histories.cs
  src/ViewModels/Repository.cs
  src/Views/AddWorktree.axaml.cs
  src/Views/Clone.axaml.cs
  src/Views/Preference.axaml.cs
  src/Views/WelcomeToolbar.axaml.cs
Labels: enhancement

#416 enhance: make HEAD commit badge highlight
  src/Views/CommitRefsPresenter.cs
Labels: enhancement

#419 Fix and add DE localization keys
  src/Resources/Locales/de_DE.axaml
Labels: localization

#420 Add support for foot
  src/Native/Linux.cs
Labels: enhancement

#422 Add Enter as keybinding for staging/unstaging
  src/Views/WorkingCopy.axaml.cs
Labels: enhancement

#428 Reset file to parent revision - improvements
  src/Commands/Checkout.cs
  src/ViewModels/CommitDetail.cs
Labels: enhancement
