Repository sourcegit-scm/sourcegit, pull requests merged in 2024-05, with the labels that each got.

#122 fix: avoid potential IndexOutOfRangeException in Models.User
  src/Models/User.cs
Labels: enhancement

#123 feat: Add config of auto fetch interval
  src/Commands/Fetch.cs
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/zh_CN.axaml
  src/ViewModels/Preference.cs
  src/Views/Preference.axaml
Labels: enhancement

#124 Enhance launcherTabsScroller scroll behavior
  src/Resources/Styles.axaml
  src/Views/Launcher.axaml
  src/Views/Launcher.axaml.cs
Labels: bug, enhancement

#153 Fix the crash caused by pushing without a branch
  src/ViewModels/Repository.cs
Labels: bug
