Repository sourcegit-scm/sourcegit, pull requests merged in 2024-11, with the labels that each got.

#641 localiztion: update
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#644 feature/autofocus password input field
  src/Views/Askpass.axaml
  src/Views/Askpass.axaml.cs
Labels: enhancement

#648 feature: add support for Visual Studio as external tool
  README.md
  src/Models/ExternalTool.cs
  src/Native/Windows.cs
Labels: enhancement

#652 feature: diff - toggle show all lines (#615)
  src/Models/DiffResult.cs
  src/Resources/Icons.axaml
  src/Resources/Locales/en_US.axaml
  src/ViewModels/DiffContext.cs
  src/ViewModels/Preference.cs
  src/Views/DiffView.axaml
  src/Views/TextDiffView.axaml.cs
Labels: enhancement

#655 Add missing translations in spanish
  src/Resources/Locales/es_ES.axaml
Labels: localization

#657 Adding hotkeys for creating branch, pushing and pulling
  src/Resources/Locales/en_US.axaml
  src/ViewModels/Histories.cs
  src/Views/Histories.axaml.cs
  src/Views/Hotkeys.axaml
  src/Views/RepositoryToolbar.axaml
Labels: enhancement

#666 update translation for russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#668 Adding missing pt_BR translation keys
  src/Resources/Locales/pt_BR.axaml
Labels: localization

#671 Allow merging tags into branches
  src/Resources/Locales/de_DE.axaml
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/ViewModels/Histories.cs
Labels: enhancement

#672 Several commit links improvements
  src/ViewModels/CommitDetail.cs
Labels: enhancement

#676 Update spanish translation
  src/Resources/Locales/es_ES.axaml
Labels: localization

#680 update translation for russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#688 enhance: depend on SO in rpm package
  .editorconfig
  .gitattributes
  build/resources/rpm/SPECS/build.spec
  build/scripts/package.linux.sh
  build/scripts/package.osx-app.sh
  build/scripts/package.windows-portable.sh
Labels: bug

#689 fix: SourceGit misspelled as "Source Git"
  .github/workflows/package.yml
  build/resources/_common/applications/sourcegit.desktop
Labels: enhancement

#692 feat: delete orphan remote tracking branches
  src/Commands/Branch.cs
  src/ViewModels/DeleteBranch.cs
Labels: enhancement

#696 Add missing fr_FR keys
  TRANSLATION.md
  src/Resources/Locales/fr_FR.axaml
Labels: localization

#700 update translation for russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#708 File histories from commit view
  src/ViewModels/CommitDetail.cs
  src/ViewModels/FileHistories.cs
Labels: enhancement

#709 Add and improve de_DE keys
  src/Resources/Locales/de_DE.axaml
Labels: localization

#712 Switch WinMerge from 3-way merge to 2-way merge
  src/Models/ExternalMerger.cs
Labels: enhancement

#714 Reset Mode Hotkey
  src/Models/ResetMode.cs
  src/Views/Reset.axaml
  src/Views/Reset.axaml.cs
Labels: enhancement

#711 Slightly improve statistics
  src/Commands/Statistics.cs
  src/Models/Statistics.cs
Labels: enhancement

#719 enhance: introduce template engine for commit templates
  src/Models/CommitTemplate.cs
  src/Models/TemplateEngine.cs
Labels: enhancement

#722 update pt-BR strings
  README.md
  TRANSLATION.md
  src/Resources/Locales/pt_BR.axaml
Labels: localization

#710 Show the list of children in the commit details
  src/Commands/QueryCommitChildren.cs
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/fr_FR.axaml
  src/ViewModels/CommitDetail.cs
  src/ViewModels/Preference.cs
  src/Views/CommitBaseInfo.axaml
  src/Views/CommitBaseInfo.axaml.cs
  src/Views/CommitDetail.axaml
  src/Views/Preference.axaml
Labels: enhancement

#731 Fix spelling mistakes
  src/Resources/Locales/en_US.axaml
Labels: localization

#736 fix: don't reverse commit order when cherry-picking
  src/ViewModels/CherryPick.cs
Labels: bug

#735 Better https regex for the repo url
  src/Models/Remote.cs
Labels: enhancement

#734 feat: context menu for a commit in commit message
  src/Resources/Locales/de_DE.axaml
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/Views/CommitMessagePresenter.cs
Labels: enhancement

#741 Crash on goto to SHA, NullReferenceException
  src/Views/CommitMessagePresenter.cs
Labels: bug

#737 Add missing de_DE keys
  src/Resources/Locales/de_DE.axaml
Labels: localization

#738 localization: update
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#739 localization: update zh_TW.axaml
  src/Resources/Locales/zh_TW.axaml
Labels: localization

#759 Italian translation
  TRANSLATION.md
  src/App.axaml
  src/Models/Locales.cs
  src/Resources/Locales/it_IT.axaml
Labels: localization

#762 fix ita locale: add ResourceInclude en_US.axaml
  TRANSLATION.md
  src/Resources/Locales/it_IT.axaml
Labels: localization

#769 localization: add de_DE key for FilterCommits
  src/Resources/Locales/de_DE.axaml
Labels: localization

#770 [fix] OnSHAPressed avoid right click nav
  src/Views/CommitBaseInfo.axaml.cs
Labels: bug
