Repository sourcegit-scm/sourcegit, pull requests merged in 2024-12, with the labels that each got.

#772 localization: update
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#780 Added repositories for deb/rpm packages on buildkite
  .github/workflows/publish-packages.yml
  .github/workflows/release.yml
  SourceGit.sln
Labels: enhancement, os-linux

#791 Update Spanish translation
  README.md
  TRANSLATION.md
  src/Resources/Locales/es_ES.axaml
Labels: localization

#703 Add navigation and highlighting of change-blocks in Text Diff (#616, #717)
  src/Commands/Diff.cs
  src/Models/DiffResult.cs
  src/Resources/Icons.axaml
  src/Resources/Locales/en_US.axaml
  src/ViewModels/DiffContext.cs
  src/ViewModels/Preference.cs
  src/ViewModels/TwoSideTextDiff.cs
  src/Views/DiffView.axaml
  src/Views/DiffView.axaml.cs
  src/Views/TextDiffView.axaml
  src/Views/TextDiffView.axaml.cs
Labels: enhancement

#794 localization: update
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#798 added appimagehub link
  README.md
Labels: documentation

#797 Add repository instructions to readme
  README.md
Labels: documentation

#813 enhance: improve readability of default clone dir error messages.
  src/ViewModels/Welcome.cs
Labels: enhancement

#825 Change text selection brush to improve readability
  src/Resources/Styles.axaml
Labels: enhancement

#827 Add/fix Russian translation
  TRANSLATION.md
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#838 Fix grammar in tip
  src/Resources/Locales/en_US.axaml
Labels: localization

#839 Fix some more messages in russian and english
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#843 fix: Enter key does not stage/unstage all selected items
  src/Views/ChangeCollectionView.axaml.cs
Labels: bug

#845 localization: update
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#849 Update spanish translation
  src/Resources/Locales/es_ES.axaml
Labels: localization

#852 Support several more variants of git installation on MacOS
  src/Native/MacOS.cs
Labels: enhancement
