Repository sourcegit-scm/sourcegit, pull requests merged in 2024-09, with the labels that each got.

#431 Improve macOS window control button colors for native appearance
  src/Resources/Styles.axaml
  src/Resources/Themes.axaml
  src/Views/About.axaml
  src/Views/Askpass.axaml
  src/Views/AssumeUnchangedManager.axaml
  src/Views/CaptionButtonsMacOS.axaml
  src/Views/ConfirmRestart.axaml
  src/Views/Hotkeys.axaml
  src/Views/InteractiveRebase.axaml
  src/Views/LFSLocks.axaml
  src/Views/Preference.axaml
  src/Views/RepositoryConfigure.axaml
  src/Views/SelfUpdate.axaml
  src/Views/StandaloneCommitMessageEditor.axaml
  src/Views/Statistics.axaml
Labels: enhancement

#433 Update Traditional Chinese translation
  src/Resources/Locales/zh_TW.axaml
Labels: localization

#436 enhance: save preference.json instantly
  src/App.axaml.cs
  src/ViewModels/Preference.cs
  src/Views/Preference.axaml.cs
Labels: enhancement

#430 style(locale): Translate to French Batch 2
  src/Resources/Locales/fr_FR.axaml
Labels: localization

#453 refactor: terminal launch on macOS without temporary AppleScript
  src/Native/MacOS.cs
Labels: enhancement

#457 Add DE keys for new features
  src/Resources/Locales/de_DE.axaml
Labels: localization

#468 Allow to disable native AOT deployment
  src/SourceGit.csproj
Labels: enhancement

#474 localization: update zh_TW.axaml
  src/Resources/Locales/zh_TW.axaml
Labels: localization

#475 Add DE keys for new OpenAI commit message generation
  src/Resources/Locales/de_DE.axaml
Labels: localization

#480 Few terminal fixes
  src/Models/ShellOrTerminal.cs
  src/Native/Linux.cs
  src/Native/OS.cs
  src/Native/Windows.cs
  src/ViewModels/Preference.cs
Labels: enhancement

#494 Add syntax highlighting for Kotlin
  src/Models/TextMateHelper.cs
  src/Resources/Grammars/kotlin.json
Labels: enhancement

#495 Add support for WezTerm
  src/Models/ShellOrTerminal.cs
  src/Native/Linux.cs
  src/Resources/Images/ShellIcons/wezterm.png
Labels: enhancement

#496 Add syntax highlighting for Haxe
  src/Models/TextMateHelper.cs
  src/Resources/Grammars/haxe.json
  src/Resources/Grammars/hxml.json
Labels: enhancement

#498 build: minor tweaks
  build/scripts/package.linux.sh
  build/scripts/package.osx-app.sh
  build/scripts/package.windows-portable.sh
Labels: enhancement

#515 Show only my locks
  src/ViewModels/LFSLocks.cs
  src/Views/LFSLocks.axaml
Labels: enhancement

#519 localization: add missing german text entries
  src/Resources/Locales/de_DE.axaml
Labels: localization

#527 enhance: reduce Minimum of History Commits setting
  src/Views/Preference.axaml
Labels: enhancement

#526 fix: avoid NRE in ContextMenuExtension
  src/Views/ContextMenuExtension.cs
Labels: bug

#529 Work on the translation
  src/Resources/Locales/ru_RU.axaml
Labels: localization
