Repository sourcegit-scm/sourcegit, pull requests merged in 2024-10, with the labels that each got.

#541 Work on the translation
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#546 enhance: append to PATH on MacOS instead of overriding it
  src/Commands/Command.cs
Labels: enhancement

#559 Work on translation
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#562 Work on translate: update
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#568 Add DE keys for new features (stash, author time, chart and cherry-pick)
  src/Resources/Locales/de_DE.axaml
Labels: localization

#573 work on translation
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#579 work on translation
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#583 fix: Display all parents even if there are more then 2
  src/Commands/QueryCommits.cs
  src/Commands/QueryCommitsWithFullMessage.cs
Labels: bug

#584 fix(histories): handle commits with breaking changes
  src/Views/Histories.axaml.cs
Labels: enhancement

#589 feature: add `${branch_name}` option to commit templates
  src/Models/CommitTemplate.cs
  src/ViewModels/WorkingCopy.cs
  src/Views/RepositoryConfigure.axaml
Labels: enhancement

#594 localization: Add missing DE keys, fix misspelling
  src/Resources/Locales/de_DE.axaml
Labels: localization

#596 feat: improve commit message generation with AI prompts
  src/Commands/GenerateCommitMessage.cs
  src/Models/OpenAI.cs
  src/Resources/Locales/en_US.axaml
  src/SourceGit.csproj
  src/ViewModels/Preference.cs
  src/Views/Preference.axaml
Labels: enhancement

#598 enhance: add GitLab Issue/MR sample rules
  src/Models/RepositorySettings.cs
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/ViewModels/RepositoryConfigure.cs
  src/Views/RepositoryConfigure.axaml
Labels: enhancement

#601 doc: Make the badges clickable and redirect to the TRANSLATION.md
  .github/workflows/localization-check.yml
  README.md
  TRANSLATION.md
  build/scripts/localization-check.js
Labels: enhancement

#604 localization: update zh_TW.axaml
  src/Resources/Locales/zh_TW.axaml
Labels: localization

#606 Localization: updating the translation
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#607 doc: add link on badges
  README.md
Labels: documentation

#624 loacaliztion: update translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#623 localization: added es_ES.axaml
  src/App.axaml
  src/Models/Locales.cs
  src/Resources/Locales/es_ES.axaml
Labels: localization

#622 fix: Make RPM builds compatible with OpenSUSE
  build/resources/rpm/SPECS/build.spec
Labels: bug

#626 enhance: show commit signer
  src/Commands/QueryCommitSignInfo.cs
  src/Models/CommitSignInfo.cs
Labels: enhancement

#627 fix bug that stuck auto fetch when pull failed & make stage area resizeable
  src/ViewModels/Pull.cs
  src/Views/WorkingCopy.axaml
Labels: enhancement

#628 fix: Make RPM builds compatible with OpenSUSE (libX11)
  build/resources/rpm/SPECS/build.spec
Labels: bug

#629 fix: query file size quote filename
  src/Commands/QueryFileSize.cs
Labels: bug

#632 localization: update
  src/Resources/Locales/ru_RU.axaml
Labels: localization
