Repository sourcegit-scm/sourcegit, pull requests merged in 2025-03, with the labels that each got.

#1038 Upgrade Avalonia and CommunityToolkit.Mvvm packages
  src/SourceGit.csproj
Labels: enhancement

#1040 enhance: Handle file mode changes for new/deleted file
  src/Commands/Diff.cs
  src/Models/DiffResult.cs
Labels: enhancement

#1041 build: Add pre-install and pre-removal scripts for DEBIAN package
  SourceGit.sln
  build/resources/deb/DEBIAN/preinst
  build/resources/deb/DEBIAN/prerm
Labels: enhancement

#1051 refactor: Improve key modifier checks and AltGr detection
  src/Views/Launcher.axaml.cs
Labels: enhancement

#1053 fix: validate result not update #1052
  src/ViewModels/Pull.cs
  src/ViewModels/Push.cs
Labels: bug

#1055 feat: Add commit Tooltip in Blame
  src/ViewModels/Blame.cs
  src/Views/Blame.axaml
  src/Views/Blame.axaml.cs
  src/Views/TextDiffView.axaml.cs
Labels: enhancement

#1056 ci: set linux build container to ubuntu:20.04
  .github/workflows/build.yml
Labels: enhancement, os-linux

#1061 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1070 update and fix translation russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1071 ci: enhance Linux and Windows package workflow
  .github/workflows/package.yml
  build/scripts/package.windows.sh
Labels: enhancement

#1073 enhance: Save Preferences after switched Workspace and closed Preferences
  src/ViewModels/Launcher.cs
  src/Views/Preferences.axaml.cs
Labels: enhancement

#1076 ci(windows): maintain SourceGit folder structure
  build/scripts/package.windows.sh
Labels: bug

#1078 fix: Force English locale in branch query command.
  src/Commands/Command.cs
  src/Commands/ExecuteCustomAction.cs
  src/Commands/QueryBranches.cs
Labels: enhancement

#1079 update russian localization
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1087 fix: schedule DWM frame extension to next render frame on Windows 10
  src/Native/Windows.cs
Labels: bug

#1092 fix: improve font string processing in SetFonts method
  src/App.axaml.cs
Labels: bug

#1093 Explicitly provided fully qualified reference for the git branch.
  src/Commands/Branch.cs
Labels: enhancement

#1096 feat: add translation for "1 hour ago" in multiple languages
  src/Resources/Locales/de_DE.axaml
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/it_IT.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/Views/CommitTimeTextBlock.cs
Labels: enhancement

#1100 feat: Add JSP grammar support
  src/Models/TextMateHelper.cs
  src/Resources/Grammars/jsp.json
Labels: enhancement

#1106 fix: improve line splitting to handle both LF and CRLF line endings
  src/Commands/CountLocalChangesWithoutUntracked.cs
  src/Commands/QueryCommitSignInfo.cs
Labels: bug

#1111 update russian localization
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1113 Add missing french translations
  src/Resources/Locales/fr_FR.axaml
Labels: localization

#1124 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1128 Adding template for Azure DevOps workitems
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/it_IT.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/ViewModels/RepositoryConfigure.cs
  src/Views/RepositoryConfigure.axaml
Labels: enhancement

#1130 chore: Update DEB package configuration with installed size
  build/resources/deb/DEBIAN/control
  build/scripts/package.linux.sh
Labels: enhancement, os-linux

#1131 fix: improve font family name handling by collapsing multiple spaces
  src/App.axaml.cs
Labels: enhancement

#1136 update and fix translation russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization
