Repository sourcegit-scm/sourcegit, pull requests merged in 2025-07, with the labels that each got.

#1484 fix: Custom Shell/Terminal or Diff/Merge Tool crash fix
  src/Views/Preferences.axaml.cs
Labels: bug

#1489 refactor: auto dispatch notifications to UI thread in `Launcher`
  src/Commands/Command.cs
  src/Commands/Discard.cs
  src/Commands/GenerateCommitMessage.cs
  src/Commands/GitFlow.cs
  src/Commands/MergeTool.cs
  src/Commands/QueryLocalChanges.cs
  src/Commands/SaveChangesAsPatch.cs
  src/Commands/SaveRevisionFile.cs
  src/Commands/UnstageChangesForAmend.cs
  src/ViewModels/ExecuteCustomAction.cs
  src/ViewModels/Launcher.cs
  src/ViewModels/RevisionCompare.cs
Labels: enhancement

#1494 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1495 enhance: respect git config `merge.ff`
  src/Models/MergeMode.cs
  src/ViewModels/Merge.cs
Labels: enhancement

#1496 fix: too many closing curly braces
  src/Views/ConfigureCustomActionControls.axaml
Labels: bug

#1497 code_style: general cleanup
  .github/workflows/build.yml
  src/App.axaml.cs
  src/Commands/Command.cs
  src/Commands/QueryCommits.cs
  src/Commands/QueryRevisionFileNames.cs
  src/Commands/Worktree.cs
  src/Models/AvatarManager.cs
  src/Models/CommitGraph.cs
  src/Models/CommitLink.cs
  src/Models/DealWithChangesAfterStashing.cs
  src/Models/DiffResult.cs
  src/Models/ExternalMerger.cs
  src/Models/TextInlineChange.cs
  src/Native/Windows.cs
  src/ViewModels/Blame.cs
  src/ViewModels/BranchCompare.cs
  src/ViewModels/BranchTreeNode.cs
  src/ViewModels/CheckoutAndFastForward.cs
  src/ViewModels/Clone.cs
  src/ViewModels/ConfigureWorkspace.cs
  src/ViewModels/ConventionalCommitMessageBuilder.cs
  src/ViewModels/CreateBranch.cs
  src/ViewModels/DiffContext.cs
  src/ViewModels/ExecuteCustomAction.cs
  src/ViewModels/Histories.cs
  src/ViewModels/LFSLocks.cs
  src/ViewModels/Launcher.cs
  src/ViewModels/Preferences.cs
  src/ViewModels/Pull.cs
  src/ViewModels/Push.cs
  src/ViewModels/RevisionCompare.cs
  src/ViewModels/RevisionFileTreeNode.cs
  src/ViewModels/StashesPage.cs
  src/ViewModels/WorkingCopy.cs
  src/Views/AddWorktree.axaml.cs
  src/Views/Blame.axaml.cs
  src/Views/BranchTree.axaml.cs
  src/Views/CaptionButtons.axaml.cs
  src/Views/ChangeCollectionView.axaml.cs
  src/Views/ChromelessWindow.cs
  src/Views/CommitDetail.axaml.cs
  src/Views/CommitRefsPresenter.cs
  src/Views/ConfirmRestart.axaml.cs
  src/Views/DiffView.axaml.cs
  src/Views/ExecuteCustomAction.axaml.cs
  src/Views/FilterModeSwitchButton.axaml.cs
  src/Views/Histories.axaml
  src/Views/Histories.axaml.cs
  src/Views/InteractiveRebase.axaml.cs
  src/Views/RepositoryConfigure.axaml
  src/Views/RepositoryToolbar.axaml.cs
  src/Views/RevisionFileTreeView.axaml.cs
  src/Views/StashChanges.axaml
  src/Views/StashSubjectPresenter.cs
  src/Views/SubmodulesView.axaml.cs
  src/Views/TagsView.axaml.cs
  src/Views/TextDiffView.axaml.cs
  src/Views/Welcome.axaml.cs
Labels: code-style

#1510 enhance: use regex to fix branch names
  src/ViewModels/CreateBranch.cs
  src/ViewModels/RenameBranch.cs
Labels: enhancement

#1524 German Translation Maintenance
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1530 Update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1533 ux: replace "histories" with "history"
  src/Resources/Locales/en_US.axaml
Labels: localization

#1532 ux: show a few more shortcuts on menu items
  src/ViewModels/Histories.cs
  src/ViewModels/WorkingCopy.cs
Labels: enhancement

#1538 fix: correct "GitHub" capitalization everywhere
  src/Models/AvatarManager.cs
  src/Models/CommitLink.cs
  src/Resources/Icons.axaml
  src/Resources/Locales/de_DE.axaml
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/it_IT.axaml
  src/Resources/Locales/ja_JP.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/Resources/Locales/ta_IN.axaml
  src/Resources/Locales/uk_UA.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/ViewModels/RepositoryConfigure.cs
  src/Views/About.axaml
  src/Views/RepositoryConfigure.axaml
Labels: code-style

#1534 enhance: diff with merger option on local changes
  src/ViewModels/WorkingCopy.cs
Labels: enhancement

#1540 refactor: streamline certain string operations
  src/App.axaml.cs
  src/Commands/Blame.cs
  src/Commands/Config.cs
  src/Commands/Diff.cs
  src/Commands/QueryBranches.cs
  src/Commands/QueryRevisionObjects.cs
  src/Commands/Statistics.cs
  src/Models/Change.cs
  src/Models/OpenAI.cs
  src/Models/Stash.cs
  src/Models/Statistics.cs
  src/Models/User.cs
  src/ViewModels/BranchTreeNode.cs
  src/ViewModels/ChangeTreeNode.cs
  src/ViewModels/CommitDetail.cs
  src/ViewModels/FileHistories.cs
  src/ViewModels/InteractiveRebase.cs
  src/ViewModels/PushRevision.cs
  src/ViewModels/SubmoduleCollection.cs
  src/ViewModels/TagCollection.cs
  src/ViewModels/WorkingCopy.cs
  src/Views/CommitMessageEditor.axaml.cs
  src/Views/CommitMessageTextBox.axaml.cs
Labels: enhancement

#1536 ux: inconsistent tabs/pages terminology
  src/Resources/Locales/en_US.axaml
Labels: localization

#1545 refactor: remove unused text resources
  src/Resources/Locales/de_DE.axaml
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/it_IT.axaml
  src/Resources/Locales/ja_JP.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/Resources/Locales/ta_IN.axaml
  src/Resources/Locales/uk_UA.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
Labels: localization

#1543 code_style: general cleanup
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/format-check.yml
  .github/workflows/localization-check.yml
  .github/workflows/package.yml
  src/App.axaml.cs
  src/Commands/Command.cs
  src/Commands/GenerateCommitMessage.cs
  src/Commands/QueryCommits.cs
  src/Commands/QueryFileContent.cs
  src/Commands/SaveChangesAsPatch.cs
  src/Commands/SaveRevisionFile.cs
  src/Commands/UnstageChangesForAmend.cs
  src/Models/AvatarManager.cs
  src/Models/Commit.cs
  src/Models/DiffOption.cs
  src/Models/ExternalTool.cs
  src/Models/IssueTrackerRule.cs
  src/Models/OpenAI.cs
  src/Models/TemplateEngine.cs
  src/Native/Linux.cs
  src/Native/MacOS.cs
  src/Native/OS.cs
  src/Native/Windows.cs
  src/Resources/Locales/en_US.axaml
  src/ViewModels/CommitDetail.cs
  src/ViewModels/ConventionalCommitMessageBuilder.cs
  src/ViewModels/ExecuteCustomAction.cs
  src/ViewModels/Histories.cs
  src/ViewModels/InitGitFlow.cs
  src/ViewModels/Preferences.cs
  src/ViewModels/Repository.cs
  src/ViewModels/RepositoryConfigure.cs
  src/ViewModels/ScanRepositories.cs
  src/Views/CommitSubjectPresenter.cs
  src/Views/ConfigureCustomActionControls.axaml
  src/Views/Histories.axaml
  src/Views/Histories.axaml.cs
  src/Views/SetSubmoduleBranch.axaml
  src/Views/SubmodulesView.axaml
  src/Views/TextDiffView.axaml.cs
  src/Views/UpdateSubmodules.axaml
Labels: code-style

#1554 Update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1556 enhance: support `--autostash` on interactive rebase
  src/Commands/Rebase.cs
  src/Resources/Locales/de_DE.axaml
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/it_IT.axaml
  src/Resources/Locales/ja_JP.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/Resources/Locales/ta_IN.axaml
  src/Resources/Locales/uk_UA.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/ViewModels/Histories.cs
  src/ViewModels/InteractiveRebase.cs
  src/Views/InteractiveRebase.axaml
Labels: enhancement

#1559 fix: escape double quotes in quoted git command strings
  src/Commands/Add.cs
  src/Commands/Apply.cs
  src/Commands/Archive.cs
  src/Commands/AssumeUnchanged.cs
  src/Commands/Blame.cs
  src/Commands/Checkout.cs
  src/Commands/Command.cs
  src/Commands/Commit.cs
  src/Commands/CompareRevisions.cs
  src/Commands/Config.cs
  src/Commands/DiffTool.cs
  src/Commands/FormatPatch.cs
  src/Commands/IsBinary.cs
  src/Commands/IsLFSFiltered.cs
  src/Commands/LFS.cs
  src/Commands/Merge.cs
  src/Commands/MergeTool.cs
  src/Commands/Move.cs
  src/Commands/QueryCommits.cs
  src/Commands/QueryFileContent.cs
  src/Commands/QueryFileSize.cs
  src/Commands/QueryRevisionObjects.cs
  src/Commands/QueryStagedFileBlobGuid.cs
  src/Commands/QuerySubmodules.cs
  src/Commands/Restore.cs
  src/Commands/SaveRevisionFile.cs
  src/Commands/Stash.cs
  src/Commands/StringExtensions.cs
  src/Commands/Submodule.cs
  src/Commands/Tag.cs
  src/Commands/Worktree.cs
Labels: bug

#1563 Update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1570 enhance: more readable command log duration
  src/Views/CommandLogTime.cs
Labels: enhancement

#1584 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: code-style

#1593 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1603 Update translate Russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1604 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1600 add gerrit change-id rule
  src/Resources/Locales/en_US.axaml
  src/ViewModels/RepositoryConfigure.cs
  src/Views/RepositoryConfigure.axaml
Labels: enhancement

#1624 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1623 Update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1635 feat: support selfhost gitlab with custom url
  src/Models/CommitLink.cs
  src/Models/Remote.cs
Labels: enhancement
