Repository sourcegit-scm/sourcegit, pull requests merged in 2025-04, with the labels that each got.

#1142 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1158 Locale fr 2504
  src/Resources/Locales/fr_FR.axaml
Labels: localization

#1157 Add Japanese localization
  src/App.axaml
  src/Models/Locales.cs
  src/Resources/Locales/ja_JP.axaml
Labels: localization

#1153 Add filterbox in Staged area, same as in Unstaged area
  src/ViewModels/WorkingCopy.cs
  src/Views/WorkingCopy.axaml
Labels: enhancement

#1162 Support Plastic SCM mergetool (as ExternalMerger)
  src/Models/ExternalMerger.cs
  src/Resources/Images/ExternalToolIcons/plastic_merge.png
Labels: enhancement

#1173 Add button for running external mergetool on ALL conflicts
  src/Commands/MergeTool.cs
  src/Models/Change.cs
  src/Resources/Locales/en_US.axaml
  src/ViewModels/WorkingCopy.cs
  src/Views/ChangeStatusIcon.cs
  src/Views/Conflict.axaml
  src/Views/WorkingCopy.axaml
Labels: enhancement

#1181 update russian localization
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1180 enhance: navigate to upstream head after fetch, pull, and merge
  src/Commands/QueryBranches.cs
  src/Models/Branch.cs
  src/ViewModels/BranchTreeNode.cs
  src/ViewModels/FastForwardWithoutCheckout.cs
  src/ViewModels/Fetch.cs
  src/ViewModels/FetchInto.cs
  src/ViewModels/Merge.cs
  src/ViewModels/Pull.cs
  src/ViewModels/Repository.cs
Labels: enhancement

#1177 refactor: improve diff handling for EOL changes and enhance text diff…
  src/Commands/Diff.cs
  src/Resources/Locales/de_DE.axaml
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/es_ES.axaml
  src/Resources/Locales/fr_FR.axaml
  src/Resources/Locales/it_IT.axaml
  src/Resources/Locales/ja_JP.axaml
  src/Resources/Locales/pt_BR.axaml
  src/Resources/Locales/ru_RU.axaml
  src/Resources/Locales/ta_IN.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/ViewModels/DiffContext.cs
  src/Views/TextDiffView.axaml.cs
Labels: enhancement

#1183 feat: add workspace-specific default clone directory functionality
  src/ViewModels/Clone.cs
  src/ViewModels/Workspace.cs
  src/Views/ConfigureWorkspace.axaml
  src/Views/ConfigureWorkspace.axaml.cs
Labels: enhancement

#1185 feat: implement IPC for opening repositories in new tabs
  src/App.axaml.cs
  src/Resources/Locales/en_US.axaml
  src/ViewModels/Preferences.cs
  src/Views/Preferences.axaml
Labels: enhancement

#1206 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1220 update Avalonia
  src/SourceGit.csproj
Labels: bug

#1233 update russian localization
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1241 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1248 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1249 localization: update zh_TW.axaml
  src/Resources/Locales/zh_TW.axaml
Labels: localization

#1255 minimize temporary strings for better performance
  src/Converters/PathConverters.cs
  src/Models/DiffResult.cs
  src/Models/Worktree.cs
  src/ViewModels/Archive.cs
  src/ViewModels/Blame.cs
  src/ViewModels/Launcher.cs
  src/Views/Histories.axaml.cs
  src/Views/TextDiffView.axaml.cs
Labels: enhancement
