Repository sourcegit-scm/sourcegit, pull requests merged in 2025-08, with the labels that each got.

#1649 Update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1660 fix: exclude main worktree by comparing with commonDir in submodules
  src/ViewModels/Repository.cs
Labels: bug

#1671 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1697 Update Russian translation
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1702 fix: the menu of copy tag name in history view
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/Views/Histories.axaml.cs
Labels: bug

#1706 localization: update zh_TW.axaml
  src/Resources/Locales/zh_TW.axaml
Labels: localization

#1708 Update Russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1709 localization: update spanish translations
  TRANSLATION.md
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1704 Update Russian translation - Welcome Page and top-level menus
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1731 Update Russian translation
  src/Resources/Locales/ru_RU.axaml
Labels: enhancement, localization

#1733 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1756 feat: add clear history button to commit message template/history dropdown
  src/Resources/Locales/en_US.axaml
  src/ViewModels/WorkingCopy.cs
  src/Views/CommitMessageTextBox.axaml.cs
Labels: enhancement

#1771 localization: update Spanish translation
  src/Resources/Locales/es_ES.axaml
Labels: localization
