Repository sourcegit-scm/sourcegit, pull requests merged in 2025-06, with the labels that each got.

#1392 [Feature] DDS image support
  src/Models/ImageDecoder.cs
  src/SourceGit.csproj
  src/ViewModels/ImageSource.cs
Labels: enhancement

#1402 refactor: collecting inlines for subjects
  src/Models/Commit.cs
  src/Models/InlineElementCollector.cs
  src/Models/IssueTrackerRule.cs
  src/ViewModels/CommitDetail.cs
  src/Views/CommitMessagePresenter.cs
  src/Views/CommitSubjectPresenter.cs
Labels: code-style

#1403 fix: issue tracker rule over keyword in subject
  src/Views/CommitSubjectPresenter.cs
Labels: enhancement

#1408 [Feature] Update blame window when clicking/navigating commits
  src/ViewModels/Blame.cs
  src/Views/Blame.axaml
  src/Views/Blame.axaml.cs
Labels: enhancement

#1417 Refactor: reduce redundant code in NumericSort.Compare()
  src/Models/NumericSort.cs
Labels: code-style

#1418 Refactor: Optimize the WorkingCopy.IsChanged() method
  src/ViewModels/WorkingCopy.cs
Labels: enhancement

#1423 Dark theme change status icons
  src/Views/ChangeStatusIcon.cs
Labels: enhancement

#1430 Add "Copy Message" to context-menu for Stash item
  src/Commands/QueryStashes.cs
  src/Resources/Locales/en_US.axaml
  src/ViewModels/StashesPage.cs
Labels: enhancement

#1442 fix: fix working tree folder path detection error
  src/Views/AddWorktree.axaml.cs
Labels: bug

#1444 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1445 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1461 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1464 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1469 code_style: general cleanup
  src/App.axaml.cs
  src/Commands/Branch.cs
  src/Commands/Command.cs
  src/Commands/QueryFileContent.cs
  src/Commands/QueryRevisionObjects.cs
  src/Commands/QueryStashes.cs
  src/Commands/SaveRevisionFile.cs
  src/Converters/FilterModeConverters.cs
  src/Converters/InteractiveRebaseActionConverters.cs
  src/Models/AvatarManager.cs
  src/Models/CommitSignInfo.cs
  src/Models/DiffResult.cs
  src/Models/GitFlow.cs
  src/Models/OpenAI.cs
  src/Native/MacOS.cs
  src/Native/OS.cs
  src/Native/Windows.cs
  src/ViewModels/Checkout.cs
  src/ViewModels/CheckoutCommit.cs
  src/ViewModels/CherryPick.cs
  src/ViewModels/CommandLog.cs
  src/ViewModels/CreateBranch.cs
  src/ViewModels/FileHistories.cs
  src/ViewModels/ImageSource.cs
  src/ViewModels/InProgressContexts.cs
  src/ViewModels/InitGitFlow.cs
  src/ViewModels/LFSFetch.cs
  src/ViewModels/LFSPull.cs
  src/ViewModels/LFSPush.cs
  src/ViewModels/PushTag.cs
  src/ViewModels/Repository.cs
  src/ViewModels/ResetWithoutCheckout.cs
  src/ViewModels/Reword.cs
  src/ViewModels/Squash.cs
  src/ViewModels/StashChanges.cs
  src/Views/AIAssistant.axaml
  src/Views/AddWorktree.axaml.cs
  src/Views/BranchTree.axaml.cs
  src/Views/ChangeViewModeSwitcher.axaml
  src/Views/Checkout.axaml
  src/Views/CheckoutAndFastForward.axaml
  src/Views/CommitRefsPresenter.cs
  src/Views/CreateBranch.axaml
  src/Views/DeinitSubmodule.axaml
  src/Views/GitFlowFinish.axaml
  src/Views/GitFlowStart.axaml
  src/Views/MoveRepositoryNode.axaml
  src/Views/Pull.axaml
  src/Views/PushRevision.axaml
  src/Views/RepositoryToolbar.axaml.cs
  src/Views/StashChanges.axaml
  src/Views/StashSubjectPresenter.cs
  src/Views/TextDiffView.axaml.cs
  src/Views/WorkingCopy.axaml
  src/Views/WorkingCopy.axaml.cs
Labels: code-style

#1474 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1475 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1472 fix: searching for tree/blob hash never-ending
  src/Commands/QuerySingleCommit.cs
Labels: bug
