Repository sourcegit-scm/sourcegit, pull requests merged in 2025-02, with the labels that each got.

#929 fix: Ensure each ImageView instance calculates its own aspect ratio
  src/Views/DiffView.axaml
  src/Views/ImageContainer.cs
Labels: bug

#931 fix: add `--include-untracked` to `stash push` for specific changes
  src/Commands/Stash.cs
Labels: bug

#932 Add missing keys and general reviewing of the Italian translation
  src/Resources/Locales/it_IT.axaml
Labels: localization

#933 fix: Improve in-progress rebase handling
  src/ViewModels/InProgressContexts.cs
  src/ViewModels/Merge.cs
  src/ViewModels/WorkingCopy.cs
  src/Views/Repository.axaml
Labels: bug

#936 refactor: Update submodules individually to avoid failures (#925)
  src/Commands/Clone.cs
  src/Commands/QuerySubmodules.cs
  src/ViewModels/Clone.cs
  src/ViewModels/UpdateSubmodules.cs
Labels: enhancement

#938 fix: support encoded url in remote
  src/Models/Remote.cs
  src/Native/Windows.cs
Labels: enhancement

#948 feat: Add stash auto-restore functionality (#947)
  src/Commands/Stash.cs
  src/Models/RepositorySettings.cs
  src/Resources/Locales/en_US.axaml
  src/Resources/Locales/zh_CN.axaml
  src/Resources/Locales/zh_TW.axaml
  src/ViewModels/StashChanges.cs
  src/Views/StashChanges.axaml
Labels: enhancement

#944 fix: adjust SHA regex pattern to min 6 chars
  src/Views/CommitMessagePresenter.cs
Labels: enhancement

#946 feat: support compare both revision in FileHistories (#786)
  src/Commands/CompareRevisions.cs
  src/Converters/IntConverters.cs
  src/ViewModels/FileHistories.cs
  src/Views/FileHistories.axaml
  src/Views/FileHistories.axaml.cs
Labels: enhancement

#956 fix: when upstream is null show CommitAndPush and stop auto push (#955)
  src/ViewModels/LauncherPage.cs
  src/ViewModels/Popup.cs
  src/ViewModels/Push.cs
  src/ViewModels/Repository.cs
  src/ViewModels/WorkingCopy.cs
  src/Views/WorkingCopy.axaml
Labels: enhancement

#967 Fix: Swap selection start and end index if selection is created from bottom to top
  src/Views/TextDiffView.axaml.cs
Labels: bug

#971 update russian localization
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#973 added missing german translations
  src/Resources/Locales/de_DE.axaml
Labels: localization

#978 feat: change worktree presentation
  src/Commands/Worktree.cs
  src/Models/Worktree.cs
  src/Views/RemoveWorktree.axaml
  src/Views/Repository.axaml
Labels: enhancement

#1007 fix: Update unstaged filed counter when unstaged files change
  src/ViewModels/WorkingCopy.cs
Labels: bug

#1014 docs: update README.md
  README.md
Labels: documentation

#1016 Add first/last buttons for block-navigation, no wrapping (#1015)
  src/Resources/Icons.axaml
  src/Resources/Locales/en_US.axaml
  src/ViewModels/BlockNavigation.cs
  src/Views/DiffView.axaml
  src/Views/DiffView.axaml.cs
  src/Views/TextDiffView.axaml.cs
Labels: enhancement

#1024 localization: add missing spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1033 Improve usability of "interactive rebase"
  src/ViewModels/Histories.cs
Labels: enhancement
