Repository sourcegit-scm/sourcegit, pull requests merged in 2025-09, with the labels that each got.

#1779 localization: update Spanish translation
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1783 fix: NRE on commit double-click
  src/ViewModels/Histories.cs
Labels: bug

#1785 feat: add Vue.js syntax highlighting
  THIRD-PARTY-LICENSES.md
  src/Models/TextMateHelper.cs
  src/Resources/Grammars/vue.json
Labels: enhancement

#1796 Update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1797 Improve image diff
  src/Converters/DoubleConverters.cs
  src/Resources/Locales/en_US.axaml
  src/ViewModels/Preferences.cs
  src/Views/ImageContainer.cs
  src/Views/ImageDiffView.axaml
Labels: enhancement

#1805 localization: update Spanish translation
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1818 fix: correct Windows version parameter in window frame fix
  src/Native/Windows.cs
Labels: bug

#1820 localization: update German translations
  src/Resources/Locales/de_DE.axaml
Labels: localization
