Repository sourcegit-scm/sourcegit, pull requests merged in 2025-01, with the labels that each got.

#853 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#857 style(locale): Translate French locale further
  src/Resources/Locales/fr_FR.axaml
Labels: localization

#859 Short list of commands needed to get started running locally
  README.md
Labels: documentation

#870 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#872 update translation russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#887 update russian localization
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#886 Update Spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#885 Remove Buildkite, add missing dependencies, README edits
  .github/workflows/publish-packages.yml
  .github/workflows/release.yml
  README.md
  SourceGit.sln
  build/resources/deb/DEBIAN/control
  build/resources/rpm/SPECS/build.spec
Labels: os-linux

#893 Add package repository instructions
  README.md
Labels: documentation

#896 style(locale): Translate French locale further
  src/Resources/Locales/fr_FR.axaml
Labels: localization

#898 Exit on Ctrl+Q
  src/Views/Hotkeys.axaml
  src/Views/Launcher.axaml
  src/Views/Launcher.axaml.cs
Labels: enhancement

#902 Fix: LFS locks does not show if the user name has a dot in it
  src/Commands/LFS.cs
Labels: bug

#905 localization: add missing de_DE keys
  src/Resources/Locales/de_DE.axaml
Labels: localization

#919 fix: prevent target branch HEAD from being changed when adding worktree
  src/Commands/Worktree.cs
  src/ViewModels/AddWorktree.cs
Labels: bug

#920 Fix `_` is not parsed in template variable name
  src/Models/TemplateEngine.cs
Labels: enhancement

#928 Add Ghostty to macOS terminals.
  src/Models/ShellOrTerminal.cs
  src/Native/MacOS.cs
  src/Resources/Images/ShellIcons/ghostty.png
Labels: enhancement
