Repository sourcegit-scm/sourcegit, pull requests merged in 2025-05, with the labels that each got.

#1269 close Repository Configuration on Esc
  src/Views/RepositoryConfigure.axaml.cs
Labels: enhancement

#1275 Add Meld as an option for External Merge Tool for the windows platform.
  src/Models/ExternalMerger.cs
Labels: enhancement

#1276 update and fix translation russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1279 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1284 update german translations
  TRANSLATION.md
  src/Resources/Locales/de_DE.axaml
Labels: localization

#1291 update and fix translation russian
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1292 minimize temporary strings for better performance
  src/Models/CommitLink.cs
  src/Models/RepositorySettings.cs
  src/Views/TextDiffView.axaml.cs
Labels: enhancement

#1301 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1302 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1300 Added support for kitty terminal on macOS and Linux.
  src/Models/ShellOrTerminal.cs
  src/Native/MacOS.cs
  src/Resources/Images/ShellIcons/kitty.png
Labels: enhancement

#1319 update russian localization
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1323 Added missing Italian keys
  src/Resources/Locales/it_IT.axaml
Labels: localization

#1329 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1328 Added workspaces shortcuts
  src/Resources/Locales/en_US.axaml
  src/ViewModels/Launcher.cs
  src/Views/Hotkeys.axaml
  src/Views/Launcher.axaml
  src/Views/Launcher.axaml.cs
Labels: enhancement

#1331 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1332 minimize temporary strings for better performance
  src/ViewModels/Histories.cs
Labels: enhancement

#1335 fix: Trim and normalize commit message history line endings
  src/Models/RepositorySettings.cs
Labels: bug

#1345 Add more FileSystemWatcher patterns, to improve refresh of submodules
  src/Models/Watcher.cs
Labels: bug

#1350 Refactoring: Move hardcoded brush/strings (for Conflict-icon) into named constants
  src/Views/ChangeStatusIcon.cs
Labels: code-style

#1355 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization

#1356 Fix IsConflictResolved check for submodule
  src/ViewModels/Conflict.cs
Labels: bug

#1360 Refactoring: Add new constant Models.Commit.EmptyTreeSHA1
  src/Commands/IsBinary.cs
  src/Models/Commit.cs
  src/Models/DiffOption.cs
  src/ViewModels/CommitDetail.cs
  src/ViewModels/StashesPage.cs
  src/ViewModels/WorkingCopy.cs
Labels: code-style

#1359 Don't show Unmerged files in Staged area
  src/ViewModels/WorkingCopy.cs
Labels: enhancement

#1363 update russian translate
  src/Resources/Locales/ru_RU.axaml
Labels: localization

#1379 localization: update spanish translations
  src/Resources/Locales/es_ES.axaml
Labels: localization
